### ISSUE TITLE
Configure multiple targets with different optimization level?

### ISSUE THREAD

**Issue by zxygentoo** [emezeske/lein-cljsbuild#442]
Say I have N targets to build, and I want to build each of them with dev/stage/prod/test settings. I like to be able to build individual targets in development and build all at once with correspond setting when deploy to stage/prod. Should I write a N x 4 map in :builds then some short one-liner script, or use some lein profile trick? What will be the preferred way to do this?

I'm new to cljs, so maybe I'm missing some obvious stuff, but searching old issues seems not solving my problem.

**Comment by mneise** [comment]
@zxygentoo Not sure if I understand your question correctly, but are you looking for something like leiningen profiles (https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md)? Additionally, running `lein cljsbuild once` will build all of your configurations, or you can pass a build id to build just one configuration.

**Comment by zxygentoo** [comment]
@mneise Let me clarify my question a bit. Let's say I have a project like this:
```
(defproject build-demo "0.0.1"
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.228"]]
  :plugins [[lein-cljsbuild "1.1.3"]]
  :clean-targets ^{:protect false} ["resources/public/js/" "target"]
  :cljsbuild {:builds {:app1-dev {:source-paths ["src/app1"]
                                  :compiler {:main build-demo.app1.core
                                             :asset-path "js/dev/out1"
                                             :output-to "resources/public/js/dev/app1.js"
                                             :output-dir "resources/public/js/dev/out1"
                                             :source-map "resources/public/js/dev/app1.js.map"}}
                        :app2-dev {:source-paths ["src/app2"]
                                   :compiler {:main build-demo.app1.core
                                              :asset-path "js/dev/out2"
                                              :output-to "resources/public/js/dev/app2.js"
                                              :output-dir "resources/public/js/dev/out2"
                                              :source-map "resources/public/js/dev/app2.js.map"}}
                        :app1 {:source-paths ["src/app1"]
                               :compiler {:output-to "resources/public/js/app1.js"
                                          :output-dir "resources/public/js/out1"
                                          :optimizations :advanced
                                          :pretty-print false}}
                        :app2 {:source-paths ["src/app2"]
                               :compiler {:output-to "resources/public/js/app2.js"
                                          :output-dir "resources/public/js/out2"
                                          :optimizations :advanced
                                          :pretty-print false}}}})
```

Then
- For development: `lein cljsbuild app1-dev app2-dev`
- For production: `lein cljsbuild app1 app2`

This is nice for SPA or project with only a couple of targets to build. But my project  have like 20 targets and counting (we're planning a rewrite in cljs from javascript). I can certainly add 40 items to :builds, but it seems quite annoying and error-prone. And, there might be more settings than dev/prod in the future.

I like to move settings into one place and keep the :builds map clear and non-duplicated. Maybe some thing like this:
- For development: 
  - `lein with-profile dev cljsbuild auto`
  - `lein with-profile dev cljsbuild auto app1 app3 ...`
- For productions
  - `lein with-profile prod cljsbuild once`
  - `lein with-profile prod cljsbuild once app3`

I did read leiningen profiles [doc](https://github.com/technomancy/leiningen/blob/stable/doc/PROFILES.md), but didn't figure out a way.

Any suggestions?

**Comment by darwin** [comment]
I'm not a [boot](https://github.com/boot-clj/boot) user (yet), but maybe you should consider switching to boot, because it will give you a sane programatic interface to your build configurations.

Anyways, the configuration you want to achieve is possible with lein profiles. It is not very elegant but it can be done with profile merging.

You can get some inspiration from my [project.clj here](https://github.com/binaryage/dirac/blob/master/project.clj). The idea is to have a "default" profile which includes all default cljsbuild settings. And then overlay it with profiles which add or override selected settings groups.

For example [here I override only :pseudo-names](https://github.com/binaryage/dirac/blob/854922e96684afd76a59a259a554bf67986e86dc/project.clj#L241). And [here I append some additional :source-paths](https://github.com/binaryage/dirac/blob/854922e96684afd76a59a259a554bf67986e86dc/project.clj#L267). I also use lein aliases heavily to expose user friendly interface to [selected combinations](https://github.com/binaryage/dirac/blob/854922e96684afd76a59a259a554bf67986e86dc/project.clj#L354).

It takes some effort to do this "configuration programming" by combining multiple maps to achieve desired results. Also remember that merging keys which are vectors means appending. You can do replacing by using a special meta data. But that's also tricky because it is buggy in some cases. Also please avoid using profile names which could clash with internal profile names like :base :system :user :provided :dev, that can lead to bloody WTF situations because some of those are implicitly used during various occasions.

**Comment by zxygentoo** [comment]
@darwin Thanks, this helps a lot!
