### ISSUE TITLE
Circular dependencies : Warn user when a namespace requires itself

### ISSUE THREAD

**Issue by Frozenlock** [emezeske/lein-cljsbuild#485]
When a namespace requires itself, the compilation hangs without an error message.
It would be nice to either throw an error, or at least print a warning message to the user.

**Comment by mneise** [comment]
Would you mind providing an example to reproduce this problem? When I tried this, I got an exception during compilation as expected.

For example, have a look at the [core.cljs file](https://github.com/emezeske/lein-cljsbuild/blob/master/example-projects/none/src/none/core.cljs#L1) in the `none` example project and change the first line to:

```clojure
(ns none.core
  (:require [none.core]))
```

Then run `lein cljsbuild once` and you should get an exception stating `Caused by: clojure.lang.ExceptionInfo: Assert failed: Circular dependency detected, none.core -> none.core`.

**Comment by Frozenlock** [comment]
Correct, can't reproduce with the newer versions.
